---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 2
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret

  externalConnectivity:
    type: LoadBalancer

  configuration:
    mms.centralUrl: http://mongodb.blocksaas.io:8080

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    # it's possible to omit 'version' completely - the bundled MongoDB binary will be used in this case
    # and no MongoDB binary will be downloaded from the Internet in this case
    # version: 4.2.2-ent
    persistent: true
    podSpec:
      cpu: '0.25'
